# Generated by Django 3.2.7 on 2021-09-23 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('setup_place', models.CharField(max_length=50, verbose_name='설치 장소')),
                ('setup_day', models.CharField(help_text='설치 날짜를 입력하시오, YYYY/MM/DD hh:mm:ss', max_length=19, verbose_name='설치 날짜')),
                ('company_name', models.CharField(help_text='업체명을 입력하시오', max_length=100, verbose_name='업체명')),
                ('display', models.CharField(help_text='해상도를 입력하시오, NxM', max_length=9, verbose_name='해상도')),
                ('max_brgt', models.IntegerField(default=0, verbose_name='최대 밝기')),
                ('player_serial', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='플레이어 Serial')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

